// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiCSLwtFHG5txICCmkEzvAmlSdLT82toQ',
    appId: '1:887977789885:android:42c1b960de752edce1ead4',
    messagingSenderId: '887977789885',
    projectId: 'empolyeefirebase-9f67f',
    storageBucket: 'empolyeefirebase-9f67f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_u29xChsrsLwonFHuvZVTjBmsVc7db8',
    appId: '1:887977789885:ios:8b4926c25b7691e0e1ead4',
    messagingSenderId: '887977789885',
    projectId: 'empolyeefirebase-9f67f',
    storageBucket: 'empolyeefirebase-9f67f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseEmpolye',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANV9QYcgMuOzMZwzO49cx6nXPN-yALO4',
    appId: '1:887977789885:web:4546eb1cf9e8380fe1ead4',
    messagingSenderId: '887977789885',
    projectId: 'empolyeefirebase-9f67f',
    authDomain: 'empolyeefirebase-9f67f.firebaseapp.com',
    storageBucket: 'empolyeefirebase-9f67f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB_u29xChsrsLwonFHuvZVTjBmsVc7db8',
    appId: '1:887977789885:ios:8b4926c25b7691e0e1ead4',
    messagingSenderId: '887977789885',
    projectId: 'empolyeefirebase-9f67f',
    storageBucket: 'empolyeefirebase-9f67f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseEmpolye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBANV9QYcgMuOzMZwzO49cx6nXPN-yALO4',
    appId: '1:887977789885:web:f12143e379dc5419e1ead4',
    messagingSenderId: '887977789885',
    projectId: 'empolyeefirebase-9f67f',
    authDomain: 'empolyeefirebase-9f67f.firebaseapp.com',
    storageBucket: 'empolyeefirebase-9f67f.firebasestorage.app',
  );

}